# copyright ############################### #
# This file is part of the Xpart Package.   #
# Copyright (c) CERN, 2026.                 #
# ######################################### #
#
# This file is generated by xpart/_generate_line_tools.py.
# Do not edit it directly.


class XpartLineAPI:
    """
    Line-bound access to Xpart particle generation helpers.

    This API is exposed as ``line.xpart``. Methods delegate to the
    corresponding ``xpart`` functions. When the underlying function accepts a
    ``line`` argument, this line is used by default unless ``line`` or
    ``tracker`` is provided explicitly.
    """

    def __init__(self, line):
        self._line = line

    @property
    def line(self):
        """Line associated with this Xpart API."""
        return self._line

    def _kwargs_with_line(self, kwargs):
        if 'line' not in kwargs and 'tracker' not in kwargs:
            kwargs['line'] = self.line
        return kwargs

    def build_particles(self, *args, **kwargs):
        """
        Build particles using this line by default.
        
        This is the ``line.xpart`` container form of ``xpart.build_particles``.
        Defaults to the line owning this ``xpart`` container.
        Explicit ``line`` or ``tracker`` arguments override the container. See
        ``xtrack.Line.build_particles`` for the full parameter list.
        """
        if 'line' in kwargs or 'tracker' in kwargs:
            import xpart as xp
            return xp.build_particles(
                *args, **self._kwargs_with_line(kwargs))
        return self.line.build_particles(*args, **kwargs)

    def generate_matched_gaussian_bunch(self, *args, **kwargs):
        """
        Generate a matched Gaussian bunch.
        
        The transverse coordinates are generated from independent Gaussian
        distributions in normalized phase space and converted to physical
        coordinates using `build_particles`. The longitudinal coordinates are
        matched to the RF bucket using `generate_longitudinal_coordinates` with
        `distribution='gaussian'`.
        
        Parameters
        ----------
        num_particles : int
            Number of macroparticles to generate.
        nemitt_x : float
            Normalized horizontal emittance in m rad.
        nemitt_y : float
            Normalized vertical emittance in m rad.
        sigma_z : float
            RMS bunch length in m.
        total_intensity_particles : float, optional
            Total bunch intensity in physical particles. If not provided, the
            particle weights are set to one.
        particle_on_co : xpart.Particles, optional
            Particle on the closed orbit used as reference for the generated bunch.
            Cannot be provided together with `particle_ref`.
        R_matrix : array_like, optional
            Linear transfer matrix passed to `build_particles`.
        circumference : float, optional
            Ring circumference in m. Required when no `line` is provided.
        momentum_compaction_factor : float, optional
            Momentum compaction factor. Required when no `line` is provided.
        rf_harmonic : float or array_like, optional
            RF harmonic number or numbers. Required when no `line` is provided.
        rf_voltage : float or array_like, optional
            RF voltage or voltages in V. Required when no `line` is provided.
        rf_phase : float or array_like, optional
            RF phase or phases in rad. Required when no `line` is provided.
        energy_ref_increment : float, optional
            Reference energy increment used for the longitudinal matching.
        tracker : xtrack.Tracker, optional
            Deprecated. Use `line` instead.
        line : xtrack.Line, optional
            Line for which the bunch is generated. If provided, missing RF and
            lattice parameters are inferred from the line.
            Defaults to the line owning this ``xpart`` container.
        particle_ref : xpart.Particles, optional
            Reference particle. If not provided, `line.particle_ref` is used when
            available. Cannot be provided together with `particle_on_co`.
        engine : str, optional
            Longitudinal matching engine passed to
            `generate_longitudinal_coordinates`.
        return_matcher : bool, optional
            If True, also return the longitudinal matcher object.
        _context : xobjects.Context, optional
            Context on which to allocate the returned particles.
        _buffer : xobjects.Buffer, optional
            Buffer on which to allocate the returned particles.
        _offset : int, optional
            Offset in `_buffer` at which to allocate the returned particles.
        **kwargs
            Additional keyword arguments passed to `generate_longitudinal_coordinates`
            and `build_particles`.
        
        Returns
        -------
        particles : xpart.Particles
            Generated matched Gaussian bunch.
        matcher : object
            Longitudinal matcher used for the generation. Returned only when
            `return_matcher` is True.
        
        Example
        -------
        
        .. code-block:: python
        
            import numpy as np
            import xtrack as xt
        
            np.random.seed(12345)
        
            circumference = 26658.883
            line = xt.Line(elements=[
                xt.LineSegmentMap(
                    length=circumference,
                    betx=1.0, qx=0.31,
                    bety=1.0, qy=0.32,
                    longitudinal_mode='linear_fixed_rf',
                    voltage_rf=16e6,
                    frequency_rf=400.8e6,
                    phase_rf=np.pi,
                    slippage_length=circumference,
                    momentum_compaction_factor=3.225e-4,
                )
            ])
            line.set_particle_ref('proton', p0c=7e12)
        
            particles = line.xpart.generate_matched_gaussian_bunch(
                num_particles=4,
                total_intensity_particles=1e11,
                nemitt_x=2e-6,
                nemitt_y=2e-6,
                sigma_z=0.08)
        
            len(particles.x)  # 4
            particles.weight  # [2.5e+10, 2.5e+10, 2.5e+10, 2.5e+10]
            particles.zeta    # [-0.077427, -0.044981, 0.025293, -0.110336]
        """
        import xpart as xp
        return xp.generate_matched_gaussian_bunch(
            *args, **self._kwargs_with_line(kwargs))

    def generate_matched_gaussian_multibunch_beam(self, *args, **kwargs):
        """
        Generate a matched Gaussian multibunch beam.
        
        Each selected bunch is generated with `generate_matched_gaussian_bunch` and
        then shifted in `zeta` according to the filled bucket positions in
        `filling_scheme`. The returned object contains the selected bunches
        concatenated in bunch-selection order.
        
        Parameters
        ----------
        filling_scheme : array_like
            One-dimensional array indicating which RF buckets are filled. Non-zero
            entries are treated as filled buckets.
        bunch_num_particles : int
            Number of macroparticles to generate per bunch.
        nemitt_x : float
            Normalized horizontal emittance in m rad.
        nemitt_y : float
            Normalized vertical emittance in m rad.
        sigma_z : float
            RMS bunch length of each bunch in m.
        bunch_intensity_particles : float, optional
            Intensity of each bunch in physical particles.
        particle_on_co : xpart.Particles, optional
            Particle on the closed orbit used as reference for the generated
            bunches. Cannot be provided together with `particle_ref`.
        R_matrix : array_like, optional
            Linear transfer matrix passed to `build_particles`.
        circumference : float, optional
            Ring circumference in m. If not provided, it is taken from `line`.
        momentum_compaction_factor : float, optional
            Momentum compaction factor passed to the longitudinal matching.
        rf_harmonic : float or array_like, optional
            RF harmonic number or numbers. Used to infer the bucket length when
            `bucket_length` is not provided.
        rf_voltage : float or array_like, optional
            RF voltage or voltages in V. Used together with `rf_harmonic` for the
            longitudinal matching and to infer the main harmonic.
        rf_phase : float or array_like, optional
            RF phase or phases in rad.
        bucket_length : float, optional
            Bucket spacing in m. If provided, `rf_harmonic` and `rf_voltage` must
            not be provided.
        energy_ref_increment : float, optional
            Reference energy increment used for the longitudinal matching.
        tracker : xtrack.Tracker, optional
            Deprecated. Use `line` instead.
        line : xtrack.Line, optional
            Line for which the beam is generated. If provided, missing RF and
            lattice parameters are inferred from the line.
            Defaults to the line owning this ``xpart`` container.
        particle_ref : xpart.Particles, optional
            Reference particle. If not provided, `line.particle_ref` is used when
            available.
        engine : str, optional
            Longitudinal matching engine passed to
            `generate_longitudinal_coordinates`.
        _context : xobjects.Context, optional
            Context on which to allocate the returned particles.
        _buffer : xobjects.Buffer, optional
            Buffer on which to allocate the returned particles.
        _offset : int, optional
            Offset in `_buffer` at which to allocate the returned particles.
        bunch_selection : iterable of int, optional
            Indices, within the list of filled buckets, of the bunches to generate.
            If not provided, all filled bunches are generated, unless MPI wake
            preparation is enabled.
        bunch_spacing_buckets : int, optional
            Spacing between consecutive entries of `filling_scheme`, expressed in
            RF buckets. The physical spacing is
            `bunch_spacing_buckets * bucket_length`.
        prepare_line_and_particles_for_mpi_wake_sim : bool, optional
            If True, split the filled bunches over MPI ranks when `bunch_selection`
            is not provided and configure the line and particles for wakefield
            simulations.
        communicator : mpi4py communicator, optional
            MPI communicator used when
            `prepare_line_and_particles_for_mpi_wake_sim` is True. If not provided,
            `mpi4py.MPI.COMM_WORLD` is used.
        **kwargs
            Additional keyword arguments passed to
            `generate_matched_gaussian_bunch`.
        
        Returns
        -------
        particles : xpart.Particles
            Particles object containing the generated selected bunches.
        
        Example
        -------
        
        .. code-block:: python
        
            import numpy as np
            import xtrack as xt
        
            np.random.seed(12345)
        
            circumference = 26658.883
            line = xt.Line(elements=[
                xt.LineSegmentMap(
                    length=circumference,
                    betx=1.0, qx=0.31,
                    bety=1.0, qy=0.32,
                    longitudinal_mode='linear_fixed_rf',
                    voltage_rf=16e6,
                    frequency_rf=400.8e6,
                    phase_rf=np.pi,
                    slippage_length=circumference,
                    momentum_compaction_factor=3.225e-4,
                )
            ])
            line.set_particle_ref('proton', p0c=7e12)
        
            filling_scheme = np.zeros(4, dtype=int)
            filling_scheme[[0, 2]] = 1
        
            particles = line.xpart.generate_matched_gaussian_multibunch_beam(
                filling_scheme=filling_scheme,
                bunch_num_particles=3,
                bunch_intensity_particles=1e11,
                nemitt_x=2e-6,
                nemitt_y=2e-6,
                sigma_z=0.08,
                bucket_length=299792458 / 400.8e6)
        
            len(particles.x)       # 6
            particles.weight[:3]   # [3.333333e+10, 3.333333e+10, 3.333333e+10]
            particles.zeta         # [-0.016377, 0.038315, -0.041555, ...]
        """
        import xpart as xp
        return xp.generate_matched_gaussian_multibunch_beam(
            *args, **self._kwargs_with_line(kwargs))

    def generate_2D_pencil_with_absolute_cut(self, *args, **kwargs):
        """
        Generate a 2D pencil distribution with a cut in physical coordinates.
        
        The requested `absolute_cut` is converted to normalized coordinates at the
        selected location using the line optics and the provided normalized
        emittances. A normalized pencil distribution is then generated with
        `generate_2D_pencil` and converted back to physical coordinates.
        
        Parameters
        ----------
        num_particles : int
            Number of points to generate.
        plane : {'x', 'y'}
            Plane in which to generate the pencil distribution.
        absolute_cut : float
            Position cut in m.
        dr_sigmas : float
            Radial thickness of the pencil distribution in units of sigma.
        side : {'+', '-'}, optional
            Side on which to generate the pencil distribution.
        tracker : xtrack.Tracker, optional
            Deprecated. Use `line` instead.
        line : xtrack.Line
            Line used to compute the optics and physical coordinates.
            Defaults to the line owning this ``xpart`` container.
        nemitt_x : float
            Normalized horizontal emittance in m rad.
        nemitt_y : float
            Normalized vertical emittance in m rad.
        at_element : int or str, optional
            Element at which the cut is defined. If not provided, the start of the
            line is used.
        match_at_s : float, optional
            Longitudinal position in m at which the cut is defined, downstream of
            `at_element`. If provided, `at_element` must also be provided.
        twiss : xtrack.TwissTable or table row, optional
            Twiss data at the selected location. If not provided, it is computed
            from `line`.
        **kwargs
            Additional keyword arguments passed to `line.twiss` and
            `line.build_particles`.
        
        Returns
        -------
        v : np.ndarray
            Physical coordinate in the selected plane, `x` for `plane='x'` or `y`
            for `plane='y'`, in m.
        pv : np.ndarray
            Conjugate physical coordinate in the selected plane, `px` for
            `plane='x'` or `py` for `plane='y'`.
        
        Example
        -------
        
        .. code-block:: python
        
            import numpy as np
            import xtrack as xt
        
            np.random.seed(12345)
        
            line = xt.Line(elements=[
                xt.LineSegmentMap(
                    length=1.0,
                    betx=2.0, qx=0.31,
                    bety=3.0, qy=0.32,
                )
            ])
            line.set_particle_ref('proton', p0c=7e12)
        
            x, px = line.xpart.generate_2D_pencil_with_absolute_cut(
                num_particles=4,
                plane='x',
                absolute_cut=2e-3,
                dr_sigmas=0.2,
                side='+',
                nemitt_x=2e-6,
                nemitt_y=2e-6,
                method='4d')
        
            x   # [0.002001065, 0.002000729, 0.002000124, 0.002001496]
            px  # [2.005039e-05, 1.110235e-05, 2.871550e-05, -3.370225e-05]
        """
        import xpart as xp
        return xp.generate_2D_pencil_with_absolute_cut(
            *args, **self._kwargs_with_line(kwargs))

    def generate_longitudinal_coordinates(self, *args, **kwargs):
        """
        Generate longitudinal coordinates matched to an RF bucket.
        
        The RF and optics parameters can be inferred from `line`, or provided
        explicitly. With the default engine, linear longitudinal elements use a
        linear Gaussian match, while nonlinear RF buckets use the PyHEADTAIL-style
        RF bucket matcher.
        
        Parameters
        ----------
        line : xtrack.Line, optional
            Line for which the longitudinal coordinates are generated.
            Defaults to the line owning this ``xpart`` container.
        num_particles : int
            Number of particles to generate.
        distribution : {'gaussian', 'parabolic', 'binomial', 'qgaussian'}, optional
            Longitudinal distribution to generate. Non-Gaussian distributions
            require `engine='single-rf-harmonic'`.
        sigma_z : float
            RMS bunch length in m.
        engine : {'linear', 'pyheadtail', 'single-rf-harmonic'}, optional
            Matching engine. If not provided, it is selected from the line.
        return_matcher : bool, optional
            If True, also return the matcher object.
        particle_ref : xpart.Particles, optional
            Reference particle. If not provided, `line.particle_ref` is used.
        mass0, q0, gamma0 : float, optional
            Reference-particle properties used when they cannot be inferred from
            `particle_ref`.
        circumference : float, optional
            Ring circumference in m. Required when no `line` is provided.
        momentum_compaction_factor : float or array_like, optional
            Momentum compaction factor.
        rf_harmonic : float or array_like, optional
            RF harmonic number or numbers.
        rf_voltage : float or array_like, optional
            RF voltage or voltages in V.
        rf_phase : float or array_like, optional
            RF phase or phases in rad.
        rf_shift_zeta : float or array_like, optional
            Longitudinal RF shifts in m.
        energy_ref_increment : float, optional
            Reference energy increment in eV.
        energy_loss_from_radiation : float, optional
            Energy loss from radiation in eV.
        tracker : xtrack.Tracker, optional
            Deprecated. Use `line` instead.
        m : float, optional
            Binomial distribution parameter.
        q : float, optional
            q-Gaussian distribution parameter.
        zeta0 : float, optional
            Reference longitudinal position in m.
        delta0 : float, optional
            Reference relative momentum deviation.
        **kwargs
            Additional keyword arguments passed to `line.twiss`.
        
        Returns
        -------
        zeta : np.ndarray
            Longitudinal position in m.
        delta : np.ndarray
            Relative momentum deviation.
        matcher : object
            Matcher object used for the generation. Returned only when
            `return_matcher` is True.
        
        Example
        -------
        
        .. code-block:: python
        
            import numpy as np
            import xtrack as xt
        
            np.random.seed(12345)
        
            circumference = 26658.883
            line = xt.Line(elements=[
                xt.LineSegmentMap(
                    length=circumference,
                    betx=1.0, qx=0.31,
                    bety=1.0, qy=0.32,
                    longitudinal_mode='linear_fixed_rf',
                    voltage_rf=16e6,
                    frequency_rf=400.8e6,
                    phase_rf=np.pi,
                    slippage_length=circumference,
                    momentum_compaction_factor=3.225e-4,
                )
            ])
            line.set_particle_ref('proton', p0c=7e12)
        
            zeta, delta = line.xpart.generate_longitudinal_coordinates(
                num_particles=4,
                sigma_z=0.08)
        
            zeta   # [-0.077427, -0.044981, 0.025293, -0.110336]
            delta  # [5.386640e-05, 1.107963e-05, 1.492215e-04, 9.183090e-05]
        """
        import xpart as xp
        return xp.generate_longitudinal_coordinates(
            *args, **self._kwargs_with_line(kwargs))

    def generate_binomial_longitudinal_coordinates(self, *args, **kwargs):
        """
        Generate longitudinal coordinates with a binomial distribution.
        
        This is a convenience wrapper around `generate_longitudinal_coordinates`
        using `distribution='binomial'` and `engine='single-rf-harmonic'`.
        
        Parameters
        ----------
        num_particles : int
            Number of particles to generate.
        nemitt_x : float, optional
            Accepted for backward compatibility; not used by this function.
        nemitt_y : float, optional
            Accepted for backward compatibility; not used by this function.
        sigma_z : float
            RMS bunch length in m.
        particle_ref : xpart.Particles
            Reference particle.
        tracker : xtrack.Tracker, optional
            Deprecated. Use `line` instead.
        line : xtrack.Line
            Line used to infer the RF and optics parameters. The line must already
            have a tracker.
            Defaults to the line owning this ``xpart`` container.
        return_matcher : bool, optional
            If True, also return the `SingleRFHarmonicMatcher` object.
        m : float, optional
            Binomial distribution parameter. Larger values give lighter tails.
        
        Returns
        -------
        zeta : np.ndarray
            Longitudinal position in m.
        delta : np.ndarray
            Relative momentum deviation.
        matcher : xpart.longitudinal.SingleRFHarmonicMatcher
            Matcher object used for the generation. Returned only when
            `return_matcher` is True.
        
        Example
        -------
        
        .. code-block:: python
        
            import numpy as np
            import xtrack as xt
        
            np.random.seed(12345)
        
            circumference = 26658.883
            line = xt.Line(elements=[
                xt.LineSegmentMap(
                    length=circumference,
                    betx=1.0, qx=0.31,
                    bety=1.0, qy=0.32,
                    longitudinal_mode='linear_fixed_rf',
                    voltage_rf=16e6,
                    frequency_rf=400.8e6,
                    phase_rf=np.pi,
                    slippage_length=circumference,
                    momentum_compaction_factor=3.225e-4,
                )
            ])
            line.set_particle_ref('proton', p0c=7e12)
            line.build_tracker()
        
            zeta, delta = line.xpart.generate_binomial_longitudinal_coordinates(
                num_particles=4,
                sigma_z=0.02,
                particle_ref=line.particle_ref,
                m=5.0)
        
            zeta   # [0.010505, -0.000003, 0.009671, 0.022121]
            delta  # [2.595701e-05, -1.073864e-05, 1.769248e-05, -7.900433e-06]
        """
        import xpart as xp
        return xp.generate_binomial_longitudinal_coordinates(
            *args, **self._kwargs_with_line(kwargs))

    def generate_parabolic_longitudinal_coordinates(self, *args, **kwargs):
        """
        Generate longitudinal coordinates with a parabolic distribution.
        
        This is a convenience wrapper around `generate_longitudinal_coordinates`
        using `distribution='parabolic'` and `engine='single-rf-harmonic'`.
        
        Parameters
        ----------
        num_particles : int
            Number of particles to generate.
        nemitt_x : float, optional
            Accepted for backward compatibility; not used by this function.
        nemitt_y : float, optional
            Accepted for backward compatibility; not used by this function.
        sigma_z : float
            RMS bunch length in m.
        particle_ref : xpart.Particles
            Reference particle.
        tracker : xtrack.Tracker, optional
            Deprecated. Use `line` instead.
        line : xtrack.Line
            Line used to infer the RF and optics parameters. The line must already
            have a tracker.
            Defaults to the line owning this ``xpart`` container.
        return_matcher : bool, optional
            If True, also return the `SingleRFHarmonicMatcher` object.
        
        Returns
        -------
        zeta : np.ndarray
            Longitudinal position in m.
        delta : np.ndarray
            Relative momentum deviation.
        matcher : xpart.longitudinal.SingleRFHarmonicMatcher
            Matcher object used for the generation. Returned only when
            `return_matcher` is True.
        
        Example
        -------
        
        .. code-block:: python
        
            import numpy as np
            import xtrack as xt
        
            np.random.seed(12345)
        
            circumference = 26658.883
            line = xt.Line(elements=[
                xt.LineSegmentMap(
                    length=circumference,
                    betx=1.0, qx=0.31,
                    bety=1.0, qy=0.32,
                    longitudinal_mode='linear_fixed_rf',
                    voltage_rf=16e6,
                    frequency_rf=400.8e6,
                    phase_rf=np.pi,
                    slippage_length=circumference,
                    momentum_compaction_factor=3.225e-4,
                )
            ])
            line.set_particle_ref('proton', p0c=7e12)
            line.build_tracker()
        
            zeta, delta = line.xpart.generate_parabolic_longitudinal_coordinates(
                num_particles=4,
                sigma_z=0.02,
                particle_ref=line.particle_ref)
        
            zeta   # [-0.029114, -0.021342, -0.016575, -0.01217]
            delta  # [-4.490284e-05, -2.297977e-05, -3.434673e-05, -9.747943e-06]
        """
        import xpart as xp
        return xp.generate_parabolic_longitudinal_coordinates(
            *args, **self._kwargs_with_line(kwargs))

    def generate_qgaussian_longitudinal_coordinates(self, *args, **kwargs):
        """
        Generate longitudinal coordinates with a q-Gaussian distribution.
        
        This is a convenience wrapper around `generate_longitudinal_coordinates`
        using `distribution='qgaussian'` and `engine='single-rf-harmonic'`. The
        longitudinal line density is proportional to
        
            [1 - (1 - q) beta tau**2]**(1 / (1 - q))
        
        where `tau = zeta / beta0`. In the limit `q -> 1`, this becomes a
        Gaussian. Values below 1 give compact, lighter-tailed profiles; values
        above 1 give heavier-tailed profiles.
        
        Parameters
        ----------
        num_particles : int
            Number of particles to generate.
        nemitt_x : float, optional
            Accepted for backward compatibility; not used by this function.
        nemitt_y : float, optional
            Accepted for backward compatibility; not used by this function.
        sigma_z : float
            RMS bunch length in m.
        particle_ref : xpart.Particles
            Reference particle.
        tracker : xtrack.Tracker, optional
            Deprecated. Use `line` instead.
        line : xtrack.Line
            Line used to infer the RF and optics parameters. The line must already
            have a tracker.
            Defaults to the line owning this ``xpart`` container.
        return_matcher : bool, optional
            If True, also return the `SingleRFHarmonicMatcher` object.
        q : float, optional
            q-Gaussian parameter.
        
        Returns
        -------
        zeta : np.ndarray
            Longitudinal position in m.
        delta : np.ndarray
            Relative momentum deviation.
        matcher : xpart.longitudinal.SingleRFHarmonicMatcher
            Matcher object used for the generation. Returned only when
            `return_matcher` is True.
        
        Example
        -------
        
        .. code-block:: python
        
            import numpy as np
            import xtrack as xt
        
            np.random.seed(12345)
        
            circumference = 26658.883
            line = xt.Line(elements=[
                xt.LineSegmentMap(
                    length=circumference,
                    betx=1.0, qx=0.31,
                    bety=1.0, qy=0.32,
                    longitudinal_mode='linear_fixed_rf',
                    voltage_rf=16e6,
                    frequency_rf=400.8e6,
                    phase_rf=np.pi,
                    slippage_length=circumference,
                    momentum_compaction_factor=3.225e-4,
                )
            ])
            line.set_particle_ref('proton', p0c=7e12)
            line.build_tracker()
        
            zeta, delta = line.xpart.generate_qgaussian_longitudinal_coordinates(
                num_particles=4,
                sigma_z=0.02,
                particle_ref=line.particle_ref,
                q=1.1)
        
            zeta   # [0.011216, 0.011326, 0.001084, -0.019956]
            delta  # [-6.535480e-05, 4.544212e-05, 2.620756e-05, 5.983244e-05]
        """
        import xpart as xp
        return xp.generate_qgaussian_longitudinal_coordinates(
            *args, **self._kwargs_with_line(kwargs))

    def generate_2D_polar_grid(self, *args, **kwargs):
        """
        Generate points on a 2D polar grid.
        
        The radial and angular grids can be provided explicitly with `r_grid` and
        `theta_grid`, or built from ranges. For each coordinate, provide either an
        explicit grid, or a range together with either a step size or a number of
        points. The returned arrays are flattened over all `(r, theta)`
        combinations.
        
        Parameters
        ----------
        r_range : tuple of float, optional
            Radial range `(r_min, r_max)`. Required if `r_grid` is not provided.
        r_grid : array_like, optional
            Explicit uniformly spaced radial grid. If provided, `r_range`, `dr`,
            and `nr` must not be provided.
        dr : float, optional
            Radial step used with `r_range`. Cannot be provided together with `nr`.
        nr : int, optional
            Number of radial points used with `r_range`. Required when `r_grid` and
            `dr` are not provided.
        theta_range : tuple of float, optional
            Angular range `(theta_min, theta_max)` in rad. Required if
            `theta_grid` is not provided.
        theta_grid : array_like, optional
            Explicit uniformly spaced angular grid in rad. If provided,
            `theta_range`, `dtheta`, and `ntheta` must not be provided.
        dtheta : float, optional
            Angular step in rad used with `theta_range`. Cannot be provided
            together with `ntheta`.
        ntheta : int, optional
            Number of angular points used with `theta_range`. Required when
            `theta_grid` and `dtheta` are not provided.
        
        Returns
        -------
        a1 : np.ndarray
            First Cartesian normalized coordinate, equal to
            `r_all * cos(theta_all)`.
        a2 : np.ndarray
            Second Cartesian normalized coordinate, equal to
            `r_all * sin(theta_all)`.
        r_all : np.ndarray
            Radial coordinate for each generated point.
        theta_all : np.ndarray
            Angular coordinate in rad for each generated point.
        
        Example
        -------
        
        .. code-block:: python
        
            import numpy as np
            import xtrack as xt
        
            line = xt.Line(elements=[], element_names=[])
        
            a1, a2, r, theta = line.xpart.generate_2D_polar_grid(
                r_range=(1.0, 2.0), nr=2,
                theta_range=(0.0, np.pi / 2), ntheta=3)
        
            a1     # [1.0, 0.707107, 0.0, 2.0, 1.414214, 0.0]
            a2     # [0.0, 0.707107, 1.0, 0.0, 1.414214, 2.0]
            r      # [1.0, 1.0, 1.0, 2.0, 2.0, 2.0]
            theta  # [0.0, 0.785398, 1.570796, 0.0, 0.785398, 1.570796]
        """
        import xpart as xp
        return xp.generate_2D_polar_grid(*args, **kwargs)

    def generate_2D_uniform_circular_sector(self, *args, **kwargs):
        """
        Generate points uniformly distributed over a 2D circular sector.
        
        The radial coordinate is sampled so that the density is uniform in area
        within the annular sector defined by `r_range` and `theta_range`.
        
        Parameters
        ----------
        num_particles : int
            Number of points to generate.
        r_range : tuple of float, optional
            Radial range `(r_min, r_max)`.
        theta_range : tuple of float, optional
            Angular range `(theta_min, theta_max)` in rad.
        
        Returns
        -------
        a1 : np.ndarray
            First Cartesian normalized coordinate, equal to
            `r_all * cos(theta_all)`.
        a2 : np.ndarray
            Second Cartesian normalized coordinate, equal to
            `r_all * sin(theta_all)`.
        r_all : np.ndarray
            Radial coordinate for each generated point.
        theta_all : np.ndarray
            Angular coordinate in rad for each generated point.
        
        Example
        -------
        
        .. code-block:: python
        
            import numpy as np
            import xtrack as xt
        
            line = xt.Line(elements=[], element_names=[])
        
            np.random.seed(12345)
        
            a1, a2, r, theta = line.xpart.generate_2D_uniform_circular_sector(
                num_particles=4,
                r_range=(1.0, 2.0),
                theta_range=(0.0, np.pi / 2))
        
            a1     # [1.222453, 0.828498, 0.0694, 0.65832]
            a2     # [1.514746, 1.123707, 1.24376, 1.086414]
            r      # [1.946496, 1.396111, 1.245695, 1.270307]
            theta  # [0.89178, 0.935479, 1.515056, 1.026008]
        """
        import xpart as xp
        return xp.generate_2D_uniform_circular_sector(*args, **kwargs)

    def generate_2D_pencil(self, *args, **kwargs):
        """
        Generate a 2D pencil distribution in normalized coordinates.
        
        The generated points lie outside a position cut and within a radial
        thickness `dr_sigmas`, expressed in units of the normalized beam size. For
        `side='+'`, the cut is applied on the positive side of the first
        coordinate; for `side='-'`, on the negative side. With `side='+-'`, the
        particles are split between the two sides.
        
        Parameters
        ----------
        num_particles : int
            Number of points to generate.
        pos_cut_sigmas : float
            Position cut in units of sigma.
        dr_sigmas : float
            Radial thickness of the pencil distribution in units of sigma.
        side : {'+', '-', '+-'}, optional
            Side on which to generate the pencil distribution.
        
        Returns
        -------
        x_norm : np.ndarray
            First normalized coordinate.
        px_norm : np.ndarray
            Second normalized coordinate.
        r_points : np.ndarray
            Radial coordinate of the generated points.
        theta_points : np.ndarray
            Angular coordinate in rad of the generated points.
        
        Example
        -------
        
        .. code-block:: python
        
            import numpy as np
            import xtrack as xt
        
            line = xt.Line(elements=[], element_names=[])
        
            np.random.seed(12345)
        
            x_norm, px_norm, r, theta = line.xpart.generate_2D_pencil(
                num_particles=4,
                pos_cut_sigmas=6.0,
                dr_sigmas=0.1,
                side='-')
        
            x_norm  # [-6.042132, -6.023206, -6.015881, -6.002956]
            px_norm # [0.785794, 0.322182, 0.178111, 0.46048]
            r       # [6.093015, 6.031817, 6.018517, 6.020591]
            theta   # [3.012266, 3.088153, 3.111994, 3.065034]
        """
        import xpart as xp
        return xp.generate_2D_pencil(*args, **kwargs)

    def generate_2D_gaussian(self, *args, **kwargs):
        """
        Generate a 2D Gaussian distribution in normalized coordinates.
        
        Both returned coordinates are sampled independently from a standard normal
        distribution.
        
        Parameters
        ----------
        num_particles : int
            Number of points to generate.
        
        Returns
        -------
        x_norm : np.ndarray
            First normalized coordinate.
        px_norm : np.ndarray
            Second normalized coordinate.
        
        Example
        -------
        
        .. code-block:: python
        
            import numpy as np
            import xtrack as xt
        
            line = xt.Line(elements=[], element_names=[])
        
            np.random.seed(12345)
        
            x_norm, px_norm = line.xpart.generate_2D_gaussian(num_particles=4)
        
            x_norm  # [-0.204708, 0.478943, -0.519439, -0.55573]
            px_norm # [1.965781, 1.393406, 0.092908, 0.281746]
        """
        import xpart as xp
        return xp.generate_2D_gaussian(*args, **kwargs)

    def generate_hypersphere_2D(self, *args, **kwargs):
        """
        Generate points uniformly distributed inside a 2D disk.
        
        The returned coordinates are normalized coordinates sampled uniformly in
        area inside a disk of radius `r`.
        
        Parameters
        ----------
        num_particles : int
            Number of points to generate.
        r : float, optional
            Radius of the disk.
        rng_seed : int, optional
            Seed for the random number generator.
        
        Returns
        -------
        x_norm : np.ndarray
            First normalized coordinate.
        px_norm : np.ndarray
            Second normalized coordinate.
        
        Example
        -------
        
        .. code-block:: python
        
            import xtrack as xt
        
            line = xt.Line(elements=[], element_names=[])
        
            x_norm, px_norm = line.xpart.generate_hypersphere_2D(
                num_particles=4,
                r=2.0,
                rng_seed=12345)
        
            x_norm  # [-1.226886, -1.860261, -0.100816, -1.760178]
            px_norm # [1.088933, -0.553751, -0.991372, 0.835044]
        """
        import xpart as xp
        return xp.generate_hypersphere_2D(*args, **kwargs)

    def generate_hypersphere_4D(self, *args, **kwargs):
        """
        Generate points uniformly distributed inside a scaled 4D hypersphere.
        
        The generated coordinates satisfy an ellipsoidal scaling where the `x` and
        `px` axes use radius `rx`, and the `y` and `py` axes use radius `ry`.
        
        Parameters
        ----------
        num_particles : int
            Number of points to generate.
        rx : float, optional
            Radius used for the `x_norm` and `px_norm` coordinates.
        ry : float, optional
            Radius used for the `y_norm` and `py_norm` coordinates.
        rng_seed : int, optional
            Seed for the random number generator.
        
        Returns
        -------
        x_norm : np.ndarray
            First horizontal normalized coordinate.
        px_norm : np.ndarray
            Second horizontal normalized coordinate.
        y_norm : np.ndarray
            First vertical normalized coordinate.
        py_norm : np.ndarray
            Second vertical normalized coordinate.
        
        Example
        -------
        
        .. code-block:: python
        
            import xtrack as xt
        
            line = xt.Line(elements=[], element_names=[])
        
            x_norm, px_norm, y_norm, py_norm = line.xpart.generate_hypersphere_4D(
                num_particles=4,
                rx=2.0,
                ry=3.0,
                rng_seed=12345)
        
            x_norm  # [-1.233699, -0.067512, 0.207331, -0.819284]
            px_norm # [1.094981, -0.663875, -1.121394, 0.97336]
            y_norm  # [-1.131601, -1.838431, 2.021932, -0.755677]
            py_norm # [-0.336848, 0.872168, 0.834211, -0.098215]
        """
        import xpart as xp
        return xp.generate_hypersphere_4D(*args, **kwargs)

    def generate_hypersphere_6D(self, *args, **kwargs):
        """
        Generate points uniformly distributed inside a scaled 6D hypersphere.
        
        The generated coordinates satisfy an ellipsoidal scaling where the `x` and
        `px` axes use radius `rx`, the `y` and `py` axes use radius `ry`, and the
        `zeta` and `pzeta` axes use radius `rzeta`.
        
        Parameters
        ----------
        num_particles : int
            Number of points to generate.
        rx : float, optional
            Radius used for the `x_norm` and `px_norm` coordinates.
        ry : float, optional
            Radius used for the `y_norm` and `py_norm` coordinates.
        rzeta : float, optional
            Radius used for the `zeta_norm` and `pzeta_norm` coordinates.
        rng_seed : int, optional
            Seed for the random number generator.
        
        Returns
        -------
        x_norm : np.ndarray
            First horizontal normalized coordinate.
        px_norm : np.ndarray
            Second horizontal normalized coordinate.
        y_norm : np.ndarray
            First vertical normalized coordinate.
        py_norm : np.ndarray
            Second vertical normalized coordinate.
        zeta_norm : np.ndarray
            First longitudinal normalized coordinate.
        pzeta_norm : np.ndarray
            Second longitudinal normalized coordinate.
        
        Example
        -------
        
        .. code-block:: python
        
            import xtrack as xt
        
            line = xt.Line(elements=[], element_names=[])
        
            x_norm, px_norm, y_norm, py_norm, zeta_norm, pzeta_norm = (
                line.xpart.generate_hypersphere_6D(
                    num_particles=4,
                    rx=2.0,
                    ry=3.0,
                    rzeta=1.5,
                    rng_seed=12345)
            )
        
            x_norm     # [-1.02114, -0.742471, -0.591355, 0.297695]
            px_norm    # [0.906322, 0.352235, 0.702565, 0.723216]
            y_norm     # [-0.936633, 0.293987, -0.545443, 1.025363]
            py_norm    # [-0.278811, -1.590091, -0.070891, -0.232398]
            zeta_norm  # [-0.040526, 0.955673, 0.46072, 0.35008]
            pzeta_norm # [-0.398511, 0.394293, -0.73395, -0.62872]
        """
        import xpart as xp
        return xp.generate_hypersphere_6D(*args, **kwargs)

